### PR TITLE
Draft Pandas Lesson 

### PR DESCRIPTION
**Pull request by tomhohenstein**
Hello! 

First - I'm not 100% sure I'm doing this right, so if this is all messed up please let me know where I have gone wrong and I'll work to fix my errors. 

I'm starting a draft of the Pandas Lesson - i.e. episode 09. I thought it best to submit this pull request well before I have a final draft to allow input (because I might be reading the lesson intent differently) and to let others know I'm working on this (and happy to work with them : ).  

Thoughts, comments, edits, and additions are all welcome.

### CODE REVIEW

**Comment by gvwilson** [comment]
This looks great so far - thanks very much!

**Comment by tomhohenstein** [comment]
I think have about a 70% draft here. Still work to do on the assignments, examples, and cleaning up the language (so it is a bit more accessible and understandable). 

One quick question - for the examples in the lesson, do I add the expected python output or does that happen behind the scenes?

**Comment by gvwilson** [comment]
Please add the Python output - and thanks again.  Please also let me know when you want this merged.

**Comment by tomhohenstein** [comment]
@gvwilson I added the python output, fixed some typos and other errors. I also added links to the pandas documentation. 

I know this is not a final draft yet but I think it is a nice step forward. We can probably merge this and let others build and refine our work. 

Thank you for your help!

**Comment by gvwilson** [comment]
This is great - thanks!

**Pull request merged**
